repos:
  - repo: local
    hooks:
      - id: increment-version
        name: Increment version in pyproject.toml
        entry: python .pre_commit_hooks/increment_version.py
        language: system
        files: "^(.*/)?pyproject\\.toml$"
